//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GiboSMS.rc
//
#define IDD_GIBOSMS_DIALOG              102
#define IDI_GIBOSMS                     107
#define IDR_MAINFRAME                   128
#define IDB_SKIN_BACKGROUND             131
#define IDD_MAIN                        132
#define IDR_TRAYMENU                    133
#define IDR_MENU_MAIN                   134
#define IDD_CONTACT                     135
#define IDD_EMAILSUBJECT                136
#define IDD_JUMPOVER                    137
#define IDD_STATUS                      138
#define IDD_SETTING                     139
#define IDD_SEARCH                      140
#define IDD_PASSWORD                    141
#define IDB_WAIT                        142
#define IDB_BG                          143
#define IDR_MENU_STATUS_NEWMSGEND       144
#define IDR_MENU_STATUS_MSGSREAD        145
#define IDR_MENU_STATUS_BACKEND         146
#define IDR_MENU_STATUS_REPEATBACKEND   147
#define IDR_MENU_WAIT                   148
#define IDB_ERROR                       149
#define IDB_SMILE0                      154
#define IDB_SMILE3                      155
#define IDB_SMILE1                      156
#define IDB_SMILE2                      157
#define IDR_WAVE_ERROR                  158
#define IDR_WAVE_SUCCESS                159
#define IDB_SMILEYS                     160
#define IDB_LOGO                        162
#define IDB_ITEMVSEOBECNE               178
#define IDB_EXPANDABLEITEM              179
#define IDB_INPUTITEM                   180
#define IDB_INPUTITEMTILE               181
#define IDB_ITEM                        182
#define IDB_ITEMAKTIVACE                183
#define IDB_ITEMAKTUALITY               184
#define IDB_ITEMDATA                    185
#define IDB_ITEMEMAIL                   186
#define IDB_ITEMMAILBOX                 187
#define IDB_ITEMMESSAGE                 188
#define IDB_ITEMNOVINKY                 189
#define IDB_ITEMOPROGRAMU               190
#define IDB_ITEMPAIDSMS                 191
#define IDB_ITEMRECEIVEDMSGS            192
#define IDB_ITEMSENTMSGS                193
#define IDB_ITEMSTATISTIKA              194
#define IDB_ITEMTILE                    195
#define IDB_ITEMTM                      196
#define IDB_SELECTEDEXPANDABLEITEM      197
#define IDB_SELECTEDINPUTITEM           198
#define IDB_SELECTEDINPUTITEMTILE       199
#define IDB_SELECTEDITEM                200
#define IDB_SELECTEDITEMAKTIVACE        201
#define IDB_SELECTEDITEMAKTUALITY       202
#define IDB_SELECTEDITEMDATA            203
#define IDB_SELECTEDITEMEMAIL           204
#define IDB_SELECTEDITEMMAILBOX         205
#define IDB_SELECTEDITEMMESSAGE         206
#define IDB_SELECTEDITEMNOVINKY         207
#define IDB_SELECTEDITEMOPROGRAMU       208
#define IDB_SELECTEDITEMPAIDSMS         209
#define IDB_SELECTEDITEMRECEIVEDMSGS    210
#define IDB_SELECTEDITEMSENTMSGS        211
#define IDB_SELECTEDITEMSTATISTIKA      212
#define IDB_SELECTEDITEMTILE            213
#define IDB_SELECTEDITEMTM              214
#define IDB_SELECTEDITEMVSEOBECNE       215
#define IDR_MENU_ADDRESSBOOK_SEND       217
#define IDR_MENU_LSTMSGSREAD            218
#define IDR_MENU_NONE                   219
#define IDR_MENU_PASSWORD               220
#define IDR_MENU_SEARCH                 221
#define IDR_MENU_SENDWAY                222
#define IDR_MENU_SETTING                223
#define IDR_MENU_ADDRESSBOOK_SHOW       226
#define IDR_MENU_CONTACT                227
#define IDR_MENU_EMAILSUBJECT           228
#define IDR_MENU_ENTERPICTOGRAM         229
#define IDR_MENU_IMPORTPHONEBOOK        230
#define IDR_MENU_INFORMATION            231
#define IDR_MENU_INSERTSMILEY           232
#define IDR_MENU_JUMPOVER               233
#define IDC_BUTTON_CLOSE                1000
#define IDC_EDIT_SRCNUM                 1000
#define IDC_EDIT_TEXT                   1000
#define IDC_BUTTON_MENU_LEFT            1001
#define IDC_EDIT_SIGN                   1001
#define IDC_BUTTON_MENU_RIGHT           1002
#define IDC_EDIT_EMAIL                  1003
#define IDC_EDIT_MSGSREADPAGE           1004
#define IDC_CHECK_REMEMBER              1004
#define IDC_EDIT_NAME                   1005
#define IDC_HOTKEY                      1005
#define IDC_CHECK_CONFIRMRECEIVER       1006
#define IDC_EDIT_NUMBER                 1006
#define IDC_STATIC_STATUS               1007
#define IDC_CHECK_RUNAFTERWINDOWSSTARTUP 1007
#define IDC_STATIC_STATUSPIC            1008
#define IDC_CHECK_WINKEY                1008
#define IDC_EDIT_PASSWORD               1009
#define IDC_EDIT_SUBJECT                1009
#define IDC_CHECK_QUITONSUCCESSFULLSEND 1010
#define IDC_EDIT_PAGESIZE               1010
#define IDC_CHECK_ALLOWSOUNDS           1011
#define IDC_EDIT_STEP                   1011
#define IDC_DATETIME_OD                 1012
#define IDC_COMBO1                      1012
#define IDC_COMBO_SKIN                  1012
#define IDC_CHECK_EXPERTMODE            1013
#define IDC_EDIT_CONTACT                1013
#define IDC_DATETIME_DO                 1014
#define IDC_EDIT_MSGSREADPAGE2          1014
#define IDC_EDIT_PROXY                  1014
#define ID_POPUP_KONEC                  32771
#define ID_POPUP_POSLATSMS              32772
#define ID_POPUP_OTEVRIT                32773
#define IDM_POSLAT                      32774
#define IDM_MOZNOSTI_SMAJLIK            32775
#define IDM_MOZNOSTI_VYMAZATMEZERY      32776
#define IDM_MOZNOSTI_VYMAZATTEXT        32777
#define IDM_MOZNOSTI_VRATITTEXT         32778
#define IDM_MOZNOSTI_CTENIZPRAV         32779
#define IDM_MOZNOSTI_INFORMACE          32780
#define IDM_MOZNOSTI_ADRESAR            32781
#define IDM_MOZNOSTI_NASTAVENI          32782
#define IDM_MOZNOSTI_KONEC              32783
#define IDM_NOVAZPRAVA_PRAZDNA          32784
#define IDM_NOVAZPRAVA_PREDCHOZI        32785
#define IDM_KONEC                       32786
#define IDM_ZPET                        32787
#define IDM_MOZNOSTI_DALSIZPRAVY        32788
#define IDM_MOZNOSTI_PREDCHOZIZPRAVY    32789
#define IDM_MOZNOSTI_PRESUNOUTSEO       32790
#define IDM_MOZNOSTI_VYHLEDAT           32791
#define IDM_MOZNOSTI_ZKOPIROVATPRVNIZPRAVU 32792
#define IDM_MOZNOSTI_ZKOPIROVATVSE      32793
#define IDM_MOZNOSTI_OBNOVIT            32794
#define IDM_OPAKOVAT                    32795
#define IDM_PRERUSIT                    32796
#define IDM_MOZNOSTI_POSLAT             32797
#define IDM_MOZNOSTI_ADRESARTELEFONU    32798
#define IDM_MOZNOSTI_ADRESARAPLIKACE    32799
#define IDM_MOZNOSTI_PRIDAT             32800
#define IDM_MOZNOSTI_UPRAVIT            32801
#define IDM_MOZNOSTI_SMAZAT             32802
#define IDM_MOZNOSTI_SMAZATVSE          32803
#define IDM_MOZNOSTI_IMPORT             32804
#define IDM_MOZNOSTI_EXPORT             32805
#define IDM_MOZNOSTI_VLOZITCISLO        32806
#define IDM_MOZNOSTI_VLOZITEMAIL        32807
#define IDM_VYBRAT                      32808
#define IDM_MOZNOSTI_DOPREDU            32809
#define IDM_MOZNOSTI_DOZADU             32810
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        240
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
