//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GiboSMS.rc
//
#define IDD_DIALOG1                     101
#define IDD_MAIN                        101
#define IDR_MENU_MAIN                   102
#define IDD_WAIT                        102
#define IDR_MENU_WAIT                   103
#define IDB_AKTUALITY                   103
#define IDD_ADDRESSBOOK                 103
#define IDB_DATA                        104
#define IDD_MAIN1                       104
#define IDD_SETTING                     104
#define IDB_ERROR                       105
#define IDD_CONTACT                     105
#define IDB_NOVINKY                     106
#define IDD_MAIN2                       106
#define IDD_STATUS                      106
#define IDB_OPROGRAMU                   107
#define IDD_INSERTSMILEY                107
#define IDB_REGISTRACE                  108
#define IDD_INFORMATION                 108
#define IDB_SMILE0                      109
#define IDD_EMAILSUBJECT                109
#define IDB_SMILE1                      110
#define IDD_IMPORTPHONEBOOK             110
#define IDD_PASSWORD                    110
#define IDB_SMILE2                      111
#define IDD_JUMPOVER                    111
#define IDB_SMILE3                      112
#define IDD_SEARCH                      112
#define IDB_SMS                         113
#define IDB_STATISTIKA                  114
#define IDB_TM                          115
#define IDB_USER                        116
#define IDB_VSEOBECNE                   117
#define IDB_WAIT                        118
#define IDI_ICON                        135
#define IDR_MENU_NONE                   139
#define IDB_BG                          140
#define IDR_MENU_ADDRESSBOOK_SEND       141
#define IDR_MENU_ADDRESSBOOK_SHOW       142
#define IDR_MENU_SETTING                143
#define IDR_MENU_CONTACT                144
#define IDR_MENU_STATUS                 145
#define IDB_SMILEYS                     148
#define IDR_MENU_INSERTSMILEY           149
#define IDR_MENU_INFORMATION            151
#define IDR_MENU_EMAILSUBJECT           152
#define IDR_MENU_IMPORTPHONEBOOK        153
#define IDR_WAVE_ERROR                  154
#define IDR_WAVE_SUCCESS                155
#define IDB_INPUTITEM                   156
#define IDB_SELECTEDITEM                157
#define IDB_ITEM                        158
#define IDB_SELECTEDEXPANDABLEITEM      159
#define IDB_SELECTEDINPUTITEM           160
#define IDB_EXPANDABLEITEM              161
#define IDB_ITEMNOVINKY                 162
#define IDB_ITEMVSEOBECNE               163
#define IDB_ITEMREGISTRACE              164
#define IDB_ITEMAKTIVACE                164
#define IDB_ITEMSTATISTIKA              165
#define IDB_ITEMTM                      166
#define IDB_ITEMOPROGRAMU               167
#define IDB_ITEMAKTUALITY               168
#define IDB_SELECTEDITEMVSEOBECNE       169
#define IDB_SELECTEDITEMNOVINKY         170
#define IDB_SELECTEDITEMOPROGRAMU       171
#define IDB_SELECTEDITEMREGISTRACE      172
#define IDB_SELECTEDITEMAKTIVACE        172
#define IDB_SELECTEDITEMSTATISTIKA      173
#define IDB_SELECTEDITEMTM              174
#define IDB_SELECTEDITEMAKTUALITY       175
#define IDB_SELECTEDITEMDATA            176
#define IDB_ITEMDATA                    177
#define IDR_MENUBAR1                    178
#define IDR_MENU_STATUS_BACKEND         179
#define IDR_MENU_STATUS_NEWMSGEND       180
#define IDR_MENU_STATUS_REPEATBACKEND   181
#define IDB_ITEMTILE                    181
#define IDB_SELECTEDITEMTILE            182
#define IDR_MENU_SENDWAY                182
#define IDB_INPUTITEMTILE               183
#define IDR_MENU_LSTMSGSREAD            183
#define IDB_SELECTEDINPUTITEMTILE       184
#define IDR_MENU_STATUS_MSGSREAD        184
#define IDR_MENU_PASSWORD               185
#define IDB_ITEMMESSAGE                 186
#define IDR_MENU_JUMPOVER               186
#define IDB_SELECTEDITEMMESSAGE         187
#define IDR_MENU_SEARCH                 187
#define IDB_ITEMEMAIL                   188
#define IDR_MENU_ENTERPICTOGRAM         188
#define IDB_SELECTEDITEMEMAIL           189
#define IDB_ITEMSENTMSGS                190
#define IDB_ITEMRECEIVEDMSGS            191
#define IDB_ITEMMAILBOX                 192
#define IDB_SELECTEDITEMRECEIVEDMSGS    193
#define IDB_SELECTEDITEMMAILBOX         194
#define IDB_SELECTEDITEMSENTMSGS        195
#define IDB_LOGO                        196
#define IDB_ITEMPAIDSMS                 197
#define IDB_SELECTEDITEMPAIDSMS         198
#define IDC_EDIT1                       1000
#define IDC_EDIT_TEXT                   1000
#define IDC_EDIT_SRCNUM                 1000
#define IDC_EDIT_TEXT2                  1001
#define IDC_EDIT3                       1001
#define IDC_EDIT_SIGN                   1001
#define IDC_LIST                        1002
#define IDC_EDIT_TEXT3                  1002
#define IDC_EDIT4                       1002
#define IDC_EDIT_ACCOUNTINGDAY          1002
#define IDC_EDIT_TEXT4                  1003
#define IDC_EDIT2                       1003
#define IDC_EDIT5                       1003
#define IDC_EDIT_EMAIL                  1003
#define IDC_CHECK1                      1004
#define IDC_CHECK_USEINTERNALPHONEBOOK  1004
#define IDC_EDIT_MSGSREADPAGE           1004
#define IDC_CHECK_REMEMBER              1004
#define IDC_EDIT6                       1005
#define IDC_EDIT_TMUSER                 1005
#define IDC_EDIT_NAME                   1005
#define IDC_CHECK2                      1006
#define IDC_CHECK_CONFIRMRECEIVER       1006
#define IDC_EDIT_NUMBER                 1006
#define IDC_EDIT7                       1007
#define IDC_EDIT_TMPWD                  1007
#define IDC_STATIC_STATUS               1007
#define IDC_CHECK3                      1008
#define IDC_CHECK_TMCONFIRMATION        1008
#define IDC_STATIC_STATUSPIC            1008
#define IDC_EDIT_SUBJECT                1009
#define IDC_EDIT_PASSWORD               1009
#define IDC_CHECK_QUITONSUCCESSFULLSEND 1010
#define IDC_EDIT_PAGESIZE               1010
#define IDC_CHECK_ALLOWSOUNDS           1011
#define IDC_EDIT_STEP                   1011
#define IDC_DATETIMEPICKER1             1012
#define IDC_DATETIME_OD                 1012
#define IDC_CHECK_TMPREFERFREESMS       1012
#define IDC_EDIT_CONTACT                1013
#define IDC_CHECK_EXPERTMODE            1013
#define IDC_DATETIME_DO                 1014
#define IDC_CUSTOM1                     1015
#define IDS_CAP_QUIT                    40003
#define IDS_CAP_SEND                    40006
#define ID_MOZNOSTI                     40007
#define IDS_CAP_MOZNOSTI                40009
#define IDM_POSLAT                      40010
#define IDS_CAP_POSLAT                  40011
#define IDM_MOZNOSTI_POSLATNAMAIL       40012
#define IDM_MOZNOSTI_KONEC              40013
#define IDM_MOZNOSTI_SMAJLK             40014
#define IDM_MOZNOSTI_SMAJLIK            40014
#define IDM_MOZNOSTI_VYMAZATMEZERY      40015
#define IDM_MOZNOSTI_VYMAZATTEXT        40016
#define IDM_MOZNOSTI_ADRES              40017
#define IDM_MOZNOSTI_ADRESAR            40017
#define IDM_MOZNOSTI_INFORMACE          40018
#define IDM_MOZNOSTI_NASTAVEN           40019
#define IDM_MOZNOSTI_NASTAVENI          40019
#define IDS_CAP_PERUIT                  40022
#define IDM_PRERUSIT                    40024
#define ID_MENUITEM40025                40025
#define IDS_CAP_MENUITEM40026           40027
#define ID_MENUITEM40028                40028
#define IDS_CAP_MENUITEM40029           40030
#define ID_MENUITEM40031                40031
#define IDS_CAP_MENUITEM40032           40033
#define IDS_CAP_ZPT                     40036
#define IDS_CAP_MONOSTI                 40039
#define IDM_MOZNOSTI_POSLAT             40040
#define IDM_MOZNOSTI_VLOZITRUCNE        40041
#define IDM_MOZNOSTI_PRIDAT             40042
#define IDM_MOZNOSTI_UPRAVIT            40043
#define IDM_MOZNOSTI_SMAZAT             40044
#define IDM_MOZNOSTI_SMAZATVE           40045
#define IDM_MOZNOSTI_EXPORT             40046
#define IDM_MOZNOSTI_IMPORT             40047
#define IDM_ZPET                        40048
#define IDS_CAP_ZPET                    40049
#define IDM_MOZNOSTI                    40050
#define IDM_MOZNOSTI_VLOZITCISLO        40051
#define IDM_MOZNOSTI_VLOZITEMAIL        40052
#define IDS_CAP_OK                      40054
#define IDS_CAP_CANCEL                  40056
#define IDM_MOZNOSTI_SMAZATVSE          40058
#define IDS_CAP_VLOIT                   40061
#define IDS_CAP_MENUITEM40066           40067
#define IDM_MONOSTI_VRATITTEXT          40068
#define IDM_MOZNOSTI_VRATITTEXT         40068
#define IDS_CAP_VYBRAT                  40073
#define IDM_VYBRAT                      40074
#define IDS_CAP_KONEC                   40076
#define IDM_KONEC                       40081
#define IDM_MOZNOSTI_ADRESARTELEFONU    40082
#define IDM_MOZNOSTI_ADRESARAPLIKACE    40083
#define IDS_CAP_X                       40085
#define ID_NOVAZPRAVA                   40086
#define IDM_NOVAZPRAVA_PRAZDNA          40087
#define IDM_NOVAZPRAVA_PREDCHOZI        40088
#define IDS_CAP_OPAKOVAT                40091
#define IDM_OPAKOVAT                    40092
#define IDS_CAP_NOVAZPRAVA              40093
#define IDM_MOZNOSTI_CTENIZPRAV         40094
#define IDM_MOZNOSTI_DALSIZPRAVY        40095
#define IDM_MOZNOSTI_PREDCHOZIZPRAVY    40096
#define IDM_MOZNOSTI_PRESUNOUTSEO       40097
#define IDM_MOZNOSTI_VYHLEDAT           40098
#define IDM_MOZNOSTI_ZKOPIROVATPRVNIZPRAVU 40099
#define IDM_MOZNOSTI_ZKOPIROVATVSE      40100
#define IDM_MOZNOSTI_OBNOVIT            40101
#define IDM_MOZNOSTI_DOPREDU            40102
#define IDM_MOZNOSTI_DOZADU             40103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         40109
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
